DELETE FROM `monasca_transform`.`pre_transform_specs`;

INSERT IGNORE INTO `monasca_transform`.`pre_transform_specs`
(`event_type`,
`pre_transform_spec`)
VALUES
('mem.total_mb',
'{"metric_id_list": ["mem_total_all"], "required_raw_fields_list": ["creation_time"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "mem.total_mb", "service_id": "host_metrics"}'),
('mem.usable_mb',
'{"metric_id_list": ["mem_usable_all"], "required_raw_fields_list": ["creation_time"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "mem.usable_mb", "service_id": "host_metrics"}'),
('vm.mem.total_mb',
'{"metric_id_list": ["vm_mem_total_mb_all", "vm_mem_total_mb_project"], "required_raw_fields_list": ["creation_time", "tenantId", "resource_id"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "vm.mem.total_mb", "service_id": "host_metrics"}'),
('vm.mem.used_mb',
'{"metric_id_list": ["vm_mem_used_mb_all", "vm_mem_used_mb_project"], "required_raw_fields_list": ["creation_time", "tenantId", "resource_id"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "vm.mem.used_mb", "service_id": "host_metrics"}'),
('nova.vm.mem.total_allocated_mb',
'{"metric_id_list": ["nova_vm_mem_total_all"], "required_raw_fields_list": ["creation_time"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "nova.vm.mem.total_allocated_mb", "service_id": "host_metrics"}'),
('disk.total_space_mb',
'{"metric_id_list": ["disk_total_all"], "required_raw_fields_list": ["creation_time"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "disk.total_space_mb", "service_id": "host_metrics"}'),
('disk.total_used_space_mb',
'{"metric_id_list": ["disk_usable_all"], "required_raw_fields_list": ["creation_time"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "disk.total_used_space_mb", "service_id": "host_metrics"}'),
('nova.vm.disk.total_allocated_gb',
'{"metric_id_list": ["nova_disk_total_allocated_gb_all"], "required_raw_fields_list": ["creation_time"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "nova.vm.disk.total_allocated_gb", "service_id": "host_metrics"}'),
('vm.disk.allocation',
'{"metric_id_list": ["vm_disk_allocation_all", "vm_disk_allocation_project"], "required_raw_fields_list": ["creation_time", "tenant_id", "resource_id"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "vm.disk.allocation", "service_id": "host_metrics"}'),
('cpu.total_logical_cores',
'{"metric_id_list": ["cpu_total_all", "cpu_total_host", "cpu_util_all", "cpu_util_host"], "required_raw_fields_list": ["creation_time"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "cpu.total_logical_cores", "service_id": "host_metrics"}'),
('cpu.idle_perc',
'{"metric_id_list": ["cpu_util_all", "cpu_util_host"], "required_raw_fields_list": ["creation_time"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "cpu.idle_perc", "service_id": "host_metrics"}'),
('vcpus',
'{"metric_id_list": ["vcpus_all", "vcpus_project"], "required_raw_fields_list": ["creation_time", "project_id", "resource_id"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "vcpus", "service_id": "host_metrics"}'),
('vm.cpu.utilization_perc',
'{"metric_id_list": ["vm_cpu_util_perc_project"], "required_raw_fields_list": ["creation_time", "tenant_id", "resource_id"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "vm.cpu.utilization_perc", "service_id": "host_metrics"}'),
('nova.vm.cpu.total_allocated',
'{"metric_id_list": ["nova_vm_cpu_total_all"], "required_raw_fields_list": ["creation_time"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "nova.vm.cpu.total_allocated", "service_id": "host_metrics"}'),
('swiftlm.diskusage.host.val.size',
'{"metric_id_list": ["swift_total_all", "swift_total_host"], "required_raw_fields_list": ["creation_time", "hostname", "mount"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "swiftlm.diskusage.host.val.size", "service_id": "host_metrics"}'),
('swiftlm.diskusage.host.val.avail',
'{"metric_id_list": ["swift_avail_all", "swift_avail_host", "swift_usage_rate"], "required_raw_fields_list": ["creation_time", "hostname", "mount"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "swiftlm.diskusage.host.val.avail", "service_id": "host_metrics"}'),
('storage.objects.size',
'{"metric_id_list": ["storage_objects_size_all"], "required_raw_fields_list": ["creation_time", "project_id"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "storage.objects.size", "service_id": "host_metrics"}'),
('pod.net.in_bytes_sec',
'{"metric_id_list": ["pod_net_in_b_per_sec_total_all", "pod_net_in_b_per_sec_per_namespace", "pod_net_in_b_per_sec_per_app"], "required_raw_fields_list": ["creation_time", "tenantId", "namespace", "pod_name", "app"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "pod.net.in_bytes_sec", "service_id": "host_metrics"}'),
('pod.net.out_bytes_sec',
'{"metric_id_list": ["pod_net_out_b_per_sec_total_all", "pod_net_out_b_per_sec_per_namespace"], "required_raw_fields_list": ["creation_time", "tenantId", "namespace", "pod_name"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "pod.net.out_bytes_sec", "service_id": "host_metrics"}'),
('pod.mem.used_bytes',
'{"metric_id_list": ["pod.mem_used_b_total_all", "pod.mem_used_b_per_pod_name", "pod.mem_used_b_per_namespace"], "required_raw_fields_list": ["creation_time", "tenantId", "namespace", "pod_name"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "pod.mem.used_bytes", "service_id": "host_metrics"}'),
('pod.cpu.total_time',
'{"metric_id_list": ["pod_cpu_total_all", "pod_cpu_per_namespace"], "required_raw_fields_list": ["creation_time", "tenantId", "namespace"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "pod.cpu.total_time", "service_id": "host_metrics"}'),
('container.cpu.total_time',
'{"metric_id_list": ["container_cpu_total_time_all", "container_cpu_total_time_per_container"], "required_raw_fields_list": ["creation_time", "tenantId", "container_name"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "container.cpu.total_time", "service_id": "host_metrics"}'),
('kubernetes.node.capacity.cpu',
'{"metric_id_list": ["kubernetes_node_capacity_cpu_all", "kubernetes_node_capacity_cpu_per_host"], "required_raw_fields_list": ["creation_time", "tenantId", "hostname"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "kubernetes.node.capacity.cpu", "service_id": "host_metrics"}'),
('cpu.total_time_sec',
'{"metric_id_list": ["cpu_total_time_sec_all", "cpu_total_time_sec_per_host"], "required_raw_fields_list": ["creation_time", "tenantId", "hostname"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "cpu.total_time_sec", "service_id": "host_metrics"}'),
('kubernetes.node.allocatable.cpu',
'{"metric_id_list": ["kubernetes_node_allocatable_cpu_all", "kubernetes_node_allocatable_cpu_per_host"], "required_raw_fields_list": ["creation_time", "tenantId", "hostname"], "event_processing_params": {"set_default_region_to": "W", "set_default_geolocation_to": "1", "set_default_zone_to": "1"}, "event_type": "kubernetes.node.allocatable.cpu", "service_id": "host_metrics"}');