{{- if .Values.alarm_definition_controller.enabled }}
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: alarm-definition.monasca.io
description: "A specification to create a Monasca alarm definition"
versions:
- name: v1
{{- end }}
